/**
 * Mapa de códigos IOC (usados pela World Athletics / Diamond League)
 * para ISO-3166-1 alpha-2 (usados pelo flagcdn) e nome em português.
 */
export const IOC_COUNTRIES: Record<string, { iso2: string; name: string }> = {
  ALG: { iso2: 'dz', name: 'Argélia' },
  AND: { iso2: 'ad', name: 'Andorra' },
  AUS: { iso2: 'au', name: 'Austrália' },
  AUT: { iso2: 'at', name: 'Áustria' },
  BAH: { iso2: 'bs', name: 'Bahamas' },
  BAR: { iso2: 'bb', name: 'Barbados' },
  BDI: { iso2: 'bi', name: 'Burundi' },
  BEL: { iso2: 'be', name: 'Bélgica' },
  BOT: { iso2: 'bw', name: 'Botsuana' },
  BRA: { iso2: 'br', name: 'Brasil' },
  BRN: { iso2: 'bh', name: 'Bahrein' },
  BUL: { iso2: 'bg', name: 'Bulgária' },
  CAN: { iso2: 'ca', name: 'Canadá' },
  CHI: { iso2: 'cl', name: 'Chile' },
  CHN: { iso2: 'cn', name: 'China' },
  CIV: { iso2: 'ci', name: 'Costa do Marfim' },
  CMR: { iso2: 'cm', name: 'Camarões' },
  COL: { iso2: 'co', name: 'Colômbia' },
  CRO: { iso2: 'hr', name: 'Croácia' },
  CUB: { iso2: 'cu', name: 'Cuba' },
  CYP: { iso2: 'cy', name: 'Chipre' },
  CZE: { iso2: 'cz', name: 'Tchéquia' },
  DEN: { iso2: 'dk', name: 'Dinamarca' },
  DMA: { iso2: 'dm', name: 'Dominica' },
  DOM: { iso2: 'do', name: 'Rep. Dominicana' },
  ECU: { iso2: 'ec', name: 'Equador' },
  EGY: { iso2: 'eg', name: 'Egito' },
  ERI: { iso2: 'er', name: 'Eritreia' },
  ESP: { iso2: 'es', name: 'Espanha' },
  ETH: { iso2: 'et', name: 'Etiópia' },
  FIN: { iso2: 'fi', name: 'Finlândia' },
  FRA: { iso2: 'fr', name: 'França' },
  GAM: { iso2: 'gm', name: 'Gâmbia' },
  GBR: { iso2: 'gb', name: 'Grã-Bretanha' },
  GER: { iso2: 'de', name: 'Alemanha' },
  GHA: { iso2: 'gh', name: 'Gana' },
  GRE: { iso2: 'gr', name: 'Grécia' },
  GRN: { iso2: 'gd', name: 'Granada' },
  HUN: { iso2: 'hu', name: 'Hungria' },
  IND: { iso2: 'in', name: 'Índia' },
  IRL: { iso2: 'ie', name: 'Irlanda' },
  ISR: { iso2: 'il', name: 'Israel' },
  ITA: { iso2: 'it', name: 'Itália' },
  IVB: { iso2: 'vg', name: 'Ilhas Virgens Br.' },
  JAM: { iso2: 'jm', name: 'Jamaica' },
  JPN: { iso2: 'jp', name: 'Japão' },
  KAZ: { iso2: 'kz', name: 'Cazaquistão' },
  KEN: { iso2: 'ke', name: 'Quênia' },
  LAT: { iso2: 'lv', name: 'Letônia' },
  LBR: { iso2: 'lr', name: 'Libéria' },
  LCA: { iso2: 'lc', name: 'Santa Lúcia' },
  LTU: { iso2: 'lt', name: 'Lituânia' },
  LUX: { iso2: 'lu', name: 'Luxemburgo' },
  MAR: { iso2: 'ma', name: 'Marrocos' },
  MEX: { iso2: 'mx', name: 'México' },
  MON: { iso2: 'mc', name: 'Mônaco' },
  MRI: { iso2: 'mu', name: 'Maurício' },
  NED: { iso2: 'nl', name: 'Holanda' },
  NGR: { iso2: 'ng', name: 'Nigéria' },
  NOR: { iso2: 'no', name: 'Noruega' },
  NZL: { iso2: 'nz', name: 'Nova Zelândia' },
  PAN: { iso2: 'pa', name: 'Panamá' },
  PER: { iso2: 'pe', name: 'Peru' },
  PHI: { iso2: 'ph', name: 'Filipinas' },
  POL: { iso2: 'pl', name: 'Polônia' },
  POR: { iso2: 'pt', name: 'Portugal' },
  PUR: { iso2: 'pr', name: 'Porto Rico' },
  QAT: { iso2: 'qa', name: 'Catar' },
  ROU: { iso2: 'ro', name: 'Romênia' },
  RSA: { iso2: 'za', name: 'África do Sul' },
  SAM: { iso2: 'ws', name: 'Samoa' },
  SEN: { iso2: 'sn', name: 'Senegal' },
  SLO: { iso2: 'si', name: 'Eslovênia' },
  SRB: { iso2: 'rs', name: 'Sérvia' },
  SRI: { iso2: 'lk', name: 'Sri Lanka' },
  SSD: { iso2: 'ss', name: 'Sudão do Sul' },
  SUI: { iso2: 'ch', name: 'Suíça' },
  SVK: { iso2: 'sk', name: 'Eslováquia' },
  SWE: { iso2: 'se', name: 'Suécia' },
  TTO: { iso2: 'tt', name: 'Trinidad e Tobago' },
  TUN: { iso2: 'tn', name: 'Tunísia' },
  TUR: { iso2: 'tr', name: 'Turquia' },
  UGA: { iso2: 'ug', name: 'Uganda' },
  UKR: { iso2: 'ua', name: 'Ucrânia' },
  URU: { iso2: 'uy', name: 'Uruguai' },
  USA: { iso2: 'us', name: 'Estados Unidos' },
  UZB: { iso2: 'uz', name: 'Uzbequistão' },
  VIN: { iso2: 'vc', name: 'São Vicente' },
  ZAM: { iso2: 'zm', name: 'Zâmbia' },
  ZIM: { iso2: 'zw', name: 'Zimbábue' },
}

export function countryName(ioc: string): string {
  return IOC_COUNTRIES[ioc]?.name ?? ioc
}

export function countryIso2(ioc: string): string | null {
  return IOC_COUNTRIES[ioc]?.iso2 ?? null
}
