import type { Meeting } from './types'

/**
 * Wanda Diamond League 2026 — calendário oficial (15 etapas).
 * Fonte: diamondleague.com. Estrutura preparada para plugar a API
 * (não oficial) da World Athletics no lugar dos resultados abaixo.
 *
 * Resultados marcados abaixo são amostras representativas com atletas
 * reais do circuito enquanto a fonte automática não está conectada.
 */
export const SEASON_YEAR = 2026

export const MEETINGS: Meeting[] = [
  {
    id: 'shanghai-2026',
    slug: 'shanghai',
    round: 1,
    name: 'Shanghai / Keqiao',
    city: 'Xangai',
    country: 'CHN',
    countryName: 'China',
    stadium: 'Keqiao Sports Centre',
    date: '2026-05-16',
    officialUrl: 'https://www.diamondleague.com/meetings/shanghai/',
    events: [
      {
        id: 'shanghai-100m-men',
        discipline: '100m',
        category: 'sprints',
        gender: 'men',
        wind: '+0.9',
        results: [
          { rank: 1, athlete: 'Kishane Thompson', country: 'JAM', mark: '9.87', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Oblique Seville', country: 'JAM', mark: '9.91', points: 7 },
          { rank: 3, athlete: 'Akani Simbine', country: 'RSA', mark: '9.96', points: 6 },
          { rank: 4, athlete: 'Ackeem Blake', country: 'JAM', mark: '10.02', points: 5 },
          { rank: 5, athlete: 'Zharnel Hughes', country: 'GBR', mark: '10.05', points: 4 },
        ],
      },
      {
        id: 'shanghai-100m-women',
        discipline: '100m',
        category: 'sprints',
        gender: 'women',
        wind: '+1.1',
        results: [
          { rank: 1, athlete: 'Julien Alfred', country: 'LCA', mark: '10.88', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Sha\u2019Carri Richardson', country: 'USA', mark: '10.94', points: 7 },
          { rank: 3, athlete: 'Shericka Jackson', country: 'JAM', mark: '10.99', points: 6 },
          { rank: 4, athlete: 'Marie-Josée Ta Lou-Smith', country: 'CIV', mark: '11.03', points: 5 },
          { rank: 5, athlete: 'Dina Asher-Smith', country: 'GBR', mark: '11.08', points: 4 },
        ],
      },
      {
        id: 'shanghai-1500m-women',
        discipline: '1500m',
        category: 'middle',
        gender: 'women',
        results: [
          { rank: 1, athlete: 'Faith Kipyegon', country: 'KEN', mark: '3:54.21', note: 'MR', points: 8 },
          { rank: 2, athlete: 'Diribe Welteji', country: 'ETH', mark: '3:55.90', points: 7 },
          { rank: 3, athlete: 'Jessica Hull', country: 'AUS', mark: '3:56.44', points: 6 },
          { rank: 4, athlete: 'Georgia Bell', country: 'GBR', mark: '3:57.80', points: 5 },
        ],
      },
      {
        id: 'shanghai-lj-men',
        discipline: 'Salto em Distância',
        category: 'jumps',
        gender: 'men',
        results: [
          { rank: 1, athlete: 'Miltiadis Tentoglou', country: 'GRE', mark: '8.32', points: 8 },
          { rank: 2, athlete: 'Wayne Pinnock', country: 'JAM', mark: '8.27', points: 7 },
          { rank: 3, athlete: 'Tajay Gayle', country: 'JAM', mark: '8.19', points: 6 },
        ],
      },
    ],
  },
  {
    id: 'xiamen-2026',
    slug: 'xiamen',
    round: 2,
    name: 'Xiamen',
    city: 'Xiamen',
    country: 'CHN',
    countryName: 'China',
    stadium: 'Egret Stadium',
    date: '2026-05-23',
    officialUrl: 'https://www.diamondleague.com/meetings/xiamen/',
    events: [
      {
        id: 'xiamen-400m-men',
        discipline: '400m',
        category: 'sprints',
        gender: 'men',
        results: [
          { rank: 1, athlete: 'Matthew Hudson-Smith', country: 'GBR', mark: '44.10', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Quincy Hall', country: 'USA', mark: '44.28', points: 7 },
          { rank: 3, athlete: 'Muzala Samukonga', country: 'ZAM', mark: '44.55', points: 6 },
        ],
      },
      {
        id: 'xiamen-3000m-men',
        discipline: '3000m',
        category: 'distance',
        gender: 'men',
        results: [
          { rank: 1, athlete: 'Jakob Ingebrigtsen', country: 'NOR', mark: '7:24.12', note: 'MR', points: 8 },
          { rank: 2, athlete: 'Berihu Aregawi', country: 'ETH', mark: '7:25.98', points: 7 },
          { rank: 3, athlete: 'Yomif Kejelcha', country: 'ETH', mark: '7:27.44', points: 6 },
        ],
      },
      {
        id: 'xiamen-100mh-women',
        discipline: '100m com Barreiras',
        category: 'hurdles',
        gender: 'women',
        wind: '+0.4',
        results: [
          { rank: 1, athlete: 'Masai Russell', country: 'USA', mark: '12.34', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Tobi Amusan', country: 'NGR', mark: '12.40', points: 7 },
          { rank: 3, athlete: 'Cyréna Samba-Mayela', country: 'FRA', mark: '12.48', points: 6 },
        ],
      },
      {
        id: 'xiamen-pv-women',
        discipline: 'Salto com Vara',
        category: 'jumps',
        gender: 'women',
        results: [
          { rank: 1, athlete: 'Katie Moon', country: 'USA', mark: '4.85', points: 8 },
          { rank: 2, athlete: 'Nina Kennedy', country: 'AUS', mark: '4.80', points: 7 },
          { rank: 3, athlete: 'Molly Caudery', country: 'GBR', mark: '4.75', points: 6 },
        ],
      },
    ],
  },
  {
    id: 'rabat-2026',
    slug: 'rabat',
    round: 3,
    name: 'Rabat',
    city: 'Rabat',
    country: 'MAR',
    countryName: 'Marrocos',
    stadium: 'Prince Moulay Abdellah',
    date: '2026-05-31',
    officialUrl: 'https://www.diamondleague.com/meetings/rabat/',
    events: [
      {
        id: 'rabat-5000m-women',
        discipline: '5000m',
        category: 'distance',
        gender: 'women',
        results: [
          { rank: 1, athlete: 'Beatrice Chebet', country: 'KEN', mark: '14:09.52', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Gudaf Tsegay', country: 'ETH', mark: '14:12.30', points: 7 },
          { rank: 3, athlete: 'Faith Cherotich', country: 'KEN', mark: '14:20.11', points: 6 },
        ],
      },
      {
        id: 'rabat-800m-men',
        discipline: '800m',
        category: 'middle',
        gender: 'men',
        results: [
          { rank: 1, athlete: 'Emmanuel Wanyonyi', country: 'KEN', mark: '1:42.20', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Marco Arop', country: 'CAN', mark: '1:42.65', points: 7 },
          { rank: 3, athlete: 'Djamel Sedjati', country: 'ALG', mark: '1:42.90', points: 6 },
        ],
      },
      {
        id: 'rabat-discus-men',
        discipline: 'Lançamento de Disco',
        category: 'throws',
        gender: 'men',
        results: [
          { rank: 1, athlete: 'Mykolas Alekna', country: 'LTU', mark: '70.12', note: 'MR', points: 8 },
          { rank: 2, athlete: 'Daniel Ståhl', country: 'SWE', mark: '68.44', points: 7 },
          { rank: 3, athlete: 'Kristjan Čeh', country: 'SLO', mark: '67.90', points: 6 },
        ],
      },
    ],
  },
  {
    id: 'rome-2026',
    slug: 'rome',
    round: 4,
    name: 'Roma',
    city: 'Roma',
    country: 'ITA',
    countryName: 'Itália',
    stadium: 'Stadio Olimpico',
    date: '2026-06-04',
    officialUrl: 'https://www.diamondleague.com/meetings/rome/',
    events: [
      {
        id: 'rome-100m-women',
        discipline: '100m',
        category: 'sprints',
        gender: 'women',
        wind: '+0.6',
        results: [
          { rank: 1, athlete: 'Julien Alfred', country: 'LCA', mark: '10.79', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Sha\u2019Carri Richardson', country: 'USA', mark: '10.85', points: 7 },
          { rank: 3, athlete: 'Melissa Jefferson-Wooden', country: 'USA', mark: '10.90', points: 6 },
        ],
      },
      {
        id: 'rome-200m-men',
        discipline: '200m',
        category: 'sprints',
        gender: 'men',
        wind: '-0.2',
        results: [
          { rank: 1, athlete: 'Noah Lyles', country: 'USA', mark: '19.68', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Letsile Tebogo', country: 'BOT', mark: '19.75', points: 7 },
          { rank: 3, athlete: 'Kenny Bednarek', country: 'USA', mark: '19.88', points: 6 },
        ],
      },
      {
        id: 'rome-3000msc-men',
        discipline: '3000m com Obstáculos',
        category: 'distance',
        gender: 'men',
        results: [
          { rank: 1, athlete: 'Soufiane El Bakkali', country: 'MAR', mark: '8:02.14', points: 8 },
          { rank: 2, athlete: 'Abraham Kibiwot', country: 'KEN', mark: '8:04.55', points: 7 },
          { rank: 3, athlete: 'Lamecha Girma', country: 'ETH', mark: '8:05.90', points: 6 },
        ],
      },
      {
        id: 'rome-hj-women',
        discipline: 'Salto em Altura',
        category: 'jumps',
        gender: 'women',
        results: [
          { rank: 1, athlete: 'Yaroslava Mahuchikh', country: 'UKR', mark: '2.02', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Nicola Olyslagers', country: 'AUS', mark: '2.00', points: 7 },
          { rank: 3, athlete: 'Eleanor Patterson', country: 'AUS', mark: '1.97', points: 6 },
        ],
      },
    ],
  },
  {
    id: 'stockholm-2026',
    slug: 'stockholm',
    round: 5,
    name: 'Estocolmo',
    city: 'Estocolmo',
    country: 'SWE',
    countryName: 'Suécia',
    stadium: 'Stockholm Olympic Stadium',
    date: '2026-06-07',
    officialUrl: 'https://www.diamondleague.com/meetings/stockholm/',
    events: [
      {
        id: 'stockholm-pv-men',
        discipline: 'Salto com Vara',
        category: 'jumps',
        gender: 'men',
        results: [
          { rank: 1, athlete: 'Armand Duplantis', country: 'SWE', mark: '6.15', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Sam Kendricks', country: 'USA', mark: '5.92', points: 7 },
          { rank: 3, athlete: 'Emmanouil Karalis', country: 'GRE', mark: '5.87', points: 6 },
        ],
      },
      {
        id: 'stockholm-1500m-men',
        discipline: '1500m',
        category: 'middle',
        gender: 'men',
        results: [
          { rank: 1, athlete: 'Jakob Ingebrigtsen', country: 'NOR', mark: '3:29.40', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Josh Kerr', country: 'GBR', mark: '3:29.88', points: 7 },
          { rank: 3, athlete: 'Yared Nuguse', country: 'USA', mark: '3:30.15', points: 6 },
        ],
      },
      {
        id: 'stockholm-400mh-women',
        discipline: '400m com Barreiras',
        category: 'hurdles',
        gender: 'women',
        results: [
          { rank: 1, athlete: 'Femke Bol', country: 'NED', mark: '51.95', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Dalilah Muhammad', country: 'USA', mark: '52.80', points: 7 },
          { rank: 3, athlete: 'Rushell Clayton', country: 'JAM', mark: '53.10', points: 6 },
        ],
      },
    ],
  },
  {
    id: 'oslo-2026',
    slug: 'oslo',
    round: 6,
    name: 'Oslo Bislett Games',
    city: 'Oslo',
    country: 'NOR',
    countryName: 'Noruega',
    stadium: 'Bislett Stadion',
    date: '2026-06-10',
    officialUrl: 'https://www.diamondleague.com/meetings/oslo/',
    events: [
      {
        id: 'oslo-5000m-men',
        discipline: '5000m',
        category: 'distance',
        gender: 'men',
        results: [
          { rank: 1, athlete: 'Jakob Ingebrigtsen', country: 'NOR', mark: '12:48.45', note: 'MR', points: 8 },
          { rank: 2, athlete: 'Grant Fisher', country: 'USA', mark: '12:50.10', points: 7 },
          { rank: 3, athlete: 'Berihu Aregawi', country: 'ETH', mark: '12:51.66', points: 6 },
        ],
      },
      {
        id: 'oslo-800m-women',
        discipline: '800m',
        category: 'middle',
        gender: 'women',
        results: [
          { rank: 1, athlete: 'Keely Hodgkinson', country: 'GBR', mark: '1:55.80', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Mary Moraa', country: 'KEN', mark: '1:56.44', points: 7 },
          { rank: 3, athlete: 'Tsige Duguma', country: 'ETH', mark: '1:57.02', points: 6 },
        ],
      },
      {
        id: 'oslo-javelin-men',
        discipline: 'Lançamento de Dardo',
        category: 'throws',
        gender: 'men',
        results: [
          { rank: 1, athlete: 'Neeraj Chopra', country: 'IND', mark: '89.34', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Julian Weber', country: 'GER', mark: '88.10', points: 7 },
          { rank: 3, athlete: 'Jakub Vadlejch', country: 'CZE', mark: '86.55', points: 6 },
        ],
      },
    ],
  },
  {
    id: 'doha-2026',
    slug: 'doha',
    round: 7,
    name: 'Doha',
    city: 'Doha',
    country: 'QAT',
    countryName: 'Catar',
    stadium: 'Suheim Bin Hamad Stadium',
    date: '2026-06-19',
    officialUrl: 'https://www.diamondleague.com/meetings/doha/',
    events: [
      {
        id: 'doha-100m-men',
        discipline: '100m',
        category: 'sprints',
        gender: 'men',
        wind: '+0.5',
        results: [
          { rank: 1, athlete: 'Kishane Thompson', country: 'JAM', mark: '9.82', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Noah Lyles', country: 'USA', mark: '9.89', points: 7 },
          { rank: 3, athlete: 'Akani Simbine', country: 'RSA', mark: '9.93', points: 6 },
        ],
      },
      {
        id: 'doha-3000msc-women',
        discipline: '3000m com Obstáculos',
        category: 'distance',
        gender: 'women',
        results: [
          { rank: 1, athlete: 'Winfred Yavi', country: 'BRN', mark: '8:58.10', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Peruth Chemutai', country: 'UGA', mark: '9:00.44', points: 7 },
          { rank: 3, athlete: 'Faith Cherotich', country: 'KEN', mark: '9:02.90', points: 6 },
        ],
      },
      {
        id: 'doha-tj-men',
        discipline: 'Salto Triplo',
        category: 'jumps',
        gender: 'men',
        results: [
          { rank: 1, athlete: 'Pedro Pichardo', country: 'POR', mark: '17.65', points: 8 },
          { rank: 2, athlete: 'Hugues Fabrice Zango', country: 'BUR', mark: '17.48', points: 7 },
          { rank: 3, athlete: 'Jordan Díaz', country: 'ESP', mark: '17.40', points: 6 },
        ],
      },
    ],
  },
  {
    id: 'paris-2026',
    slug: 'paris',
    round: 8,
    name: 'Paris',
    city: 'Paris',
    country: 'FRA',
    countryName: 'França',
    stadium: 'Stade Charléty',
    date: '2026-06-28',
    officialUrl: 'https://www.diamondleague.com/meetings/paris/',
    events: [
      {
        id: 'paris-110mh-men',
        discipline: '110m com Barreiras',
        category: 'hurdles',
        gender: 'men',
        wind: '+0.3',
        results: [
          { rank: 1, athlete: 'Grant Holloway', country: 'USA', mark: '12.98', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Daniel Roberts', country: 'USA', mark: '13.05', points: 7 },
          { rank: 3, athlete: 'Sasha Zhoya', country: 'FRA', mark: '13.11', points: 6 },
        ],
      },
      {
        id: 'paris-200m-women',
        discipline: '200m',
        category: 'sprints',
        gender: 'women',
        wind: '+0.8',
        results: [
          { rank: 1, athlete: 'Gabby Thomas', country: 'USA', mark: '21.78', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Julien Alfred', country: 'LCA', mark: '21.90', points: 7 },
          { rank: 3, athlete: 'Shericka Jackson', country: 'JAM', mark: '22.01', points: 6 },
        ],
      },
      {
        id: 'paris-lj-women',
        discipline: 'Salto em Distância',
        category: 'jumps',
        gender: 'women',
        results: [
          { rank: 1, athlete: 'Tara Davis-Woodhall', country: 'USA', mark: '7.05', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Malaika Mihambo', country: 'GER', mark: '6.98', points: 7 },
          { rank: 3, athlete: 'Larissa Iapichino', country: 'ITA', mark: '6.90', points: 6 },
        ],
      },
    ],
  },
  {
    id: 'eugene-2026',
    slug: 'eugene',
    round: 9,
    name: 'Eugene Prefontaine Classic',
    city: 'Eugene',
    country: 'USA',
    countryName: 'Estados Unidos',
    stadium: 'Hayward Field',
    date: '2026-07-04',
    officialUrl: 'https://www.diamondleague.com/meetings/eugene/',
    events: [
      {
        id: 'eugene-100m-women',
        discipline: '100m',
        category: 'sprints',
        gender: 'women',
        wind: '+1.3',
        results: [
          { rank: 1, athlete: 'Sha\u2019Carri Richardson', country: 'USA', mark: '10.72', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Julien Alfred', country: 'LCA', mark: '10.75', points: 7 },
          { rank: 3, athlete: 'Melissa Jefferson-Wooden', country: 'USA', mark: '10.81', points: 6 },
          { rank: 4, athlete: 'Twanisha Terry', country: 'USA', mark: '10.88', points: 5 },
        ],
      },
      {
        id: 'eugene-mile-men',
        discipline: 'Milha (Bowerman Mile)',
        category: 'middle',
        gender: 'men',
        results: [
          { rank: 1, athlete: 'Jakob Ingebrigtsen', country: 'NOR', mark: '3:45.60', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Yared Nuguse', country: 'USA', mark: '3:46.22', points: 7 },
          { rank: 3, athlete: 'Josh Kerr', country: 'GBR', mark: '3:46.90', points: 6 },
        ],
      },
      {
        id: 'eugene-10000m-women',
        discipline: '10.000m',
        category: 'distance',
        gender: 'women',
        results: [
          { rank: 1, athlete: 'Beatrice Chebet', country: 'KEN', mark: '28:54.14', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Gudaf Tsegay', country: 'ETH', mark: '29:05.30', points: 7 },
          { rank: 3, athlete: 'Sifan Hassan', country: 'NED', mark: '29:12.88', points: 6 },
        ],
      },
      {
        id: 'eugene-shotput-men',
        discipline: 'Arremesso de Peso',
        category: 'throws',
        gender: 'men',
        results: [
          { rank: 1, athlete: 'Ryan Crouser', country: 'USA', mark: '22.90', note: 'WL', points: 8 },
          { rank: 2, athlete: 'Joe Kovacs', country: 'USA', mark: '22.30', points: 7 },
          { rank: 3, athlete: 'Leonardo Fabbri', country: 'ITA', mark: '22.15', points: 6 },
        ],
      },
      {
        id: 'eugene-hj-men',
        discipline: 'Salto em Altura',
        category: 'jumps',
        gender: 'men',
        results: [
          { rank: 1, athlete: 'Hamish Kerr', country: 'NZL', mark: '2.34', points: 8 },
          { rank: 2, athlete: 'JuVaughn Harrison', country: 'USA', mark: '2.31', points: 7 },
          { rank: 3, athlete: 'Mutaz Essa Barshim', country: 'QAT', mark: '2.28', points: 6 },
        ],
      },
    ],
  },
  {
    id: 'monaco-2026',
    slug: 'monaco',
    round: 10,
    name: 'Monaco Herculis',
    city: 'Monaco',
    country: 'MON',
    countryName: 'Mônaco',
    stadium: 'Stade Louis II',
    date: '2026-07-10',
    officialUrl: 'https://www.diamondleague.com/meetings/monaco/',
    events: [
      { id: 'monaco-800m-men', discipline: '800m', category: 'middle', gender: 'men', results: [] },
      { id: 'monaco-1500m-women', discipline: '1500m', category: 'middle', gender: 'women', results: [] },
      { id: 'monaco-100m-men', discipline: '100m', category: 'sprints', gender: 'men', results: [] },
      { id: 'monaco-pv-men', discipline: 'Salto com Vara', category: 'jumps', gender: 'men', results: [] },
      { id: 'monaco-400mh-women', discipline: '400m com Barreiras', category: 'hurdles', gender: 'women', results: [] },
    ],
  },
  {
    id: 'london-2026',
    slug: 'london',
    round: 11,
    name: 'Londres',
    city: 'Londres',
    country: 'GBR',
    countryName: 'Reino Unido',
    stadium: 'London Stadium',
    date: '2026-07-18',
    officialUrl: 'https://www.diamondleague.com/meetings/london/',
    events: [
      { id: 'london-100m-women', discipline: '100m', category: 'sprints', gender: 'women', results: [] },
      { id: 'london-200m-men', discipline: '200m', category: 'sprints', gender: 'men', results: [] },
      { id: 'london-800m-women', discipline: '800m', category: 'middle', gender: 'women', results: [] },
      { id: 'london-5000m-men', discipline: '5000m', category: 'distance', gender: 'men', results: [] },
      { id: 'london-lj-men', discipline: 'Salto em Distância', category: 'jumps', gender: 'men', results: [] },
    ],
  },
  {
    id: 'lausanne-2026',
    slug: 'lausanne',
    round: 12,
    name: 'Lausanne Athletissima',
    city: 'Lausanne',
    country: 'SUI',
    countryName: 'Suíça',
    stadium: 'Stade de la Pontaise',
    date: '2026-08-21',
    officialUrl: 'https://www.diamondleague.com/meetings/lausanne/',
    events: [
      { id: 'lausanne-100m-men', discipline: '100m', category: 'sprints', gender: 'men', results: [] },
      { id: 'lausanne-400m-women', discipline: '400m', category: 'sprints', gender: 'women', results: [] },
      { id: 'lausanne-3000m-men', discipline: '3000m', category: 'distance', gender: 'men', results: [] },
      { id: 'lausanne-hj-women', discipline: 'Salto em Altura', category: 'jumps', gender: 'women', results: [] },
      { id: 'lausanne-javelin-men', discipline: 'Lançamento de Dardo', category: 'throws', gender: 'men', results: [] },
    ],
  },
  {
    id: 'silesia-2026',
    slug: 'silesia',
    round: 13,
    name: 'Silésia (Chorzów)',
    city: 'Chorzów',
    country: 'POL',
    countryName: 'Polônia',
    stadium: 'Stadion Śląski',
    date: '2026-08-23',
    officialUrl: 'https://www.diamondleague.com/meetings/silesia/',
    events: [
      { id: 'silesia-pv-men', discipline: 'Salto com Vara', category: 'jumps', gender: 'men', results: [] },
      { id: 'silesia-100mh-women', discipline: '100m com Barreiras', category: 'hurdles', gender: 'women', results: [] },
      { id: 'silesia-1500m-men', discipline: '1500m', category: 'middle', gender: 'men', results: [] },
      { id: 'silesia-discus-men', discipline: 'Lançamento de Disco', category: 'throws', gender: 'men', results: [] },
      { id: 'silesia-5000m-women', discipline: '5000m', category: 'distance', gender: 'women', results: [] },
    ],
  },
  {
    id: 'zurich-2026',
    slug: 'zurich',
    round: 14,
    name: 'Zurique Weltklasse',
    city: 'Zurique',
    country: 'SUI',
    countryName: 'Suíça',
    stadium: 'Letzigrund',
    date: '2026-08-27',
    officialUrl: 'https://www.diamondleague.com/meetings/zurich/',
    events: [
      { id: 'zurich-100m-men', discipline: '100m', category: 'sprints', gender: 'men', results: [] },
      { id: 'zurich-100m-women', discipline: '100m', category: 'sprints', gender: 'women', results: [] },
      { id: 'zurich-800m-men', discipline: '800m', category: 'middle', gender: 'men', results: [] },
      { id: 'zurich-400mh-men', discipline: '400m com Barreiras', category: 'hurdles', gender: 'men', results: [] },
      { id: 'zurich-tj-women', discipline: 'Salto Triplo', category: 'jumps', gender: 'women', results: [] },
    ],
  },
  {
    id: 'brussels-2026',
    slug: 'brussels',
    round: 15,
    name: 'Final — Bruxelas',
    city: 'Bruxelas',
    country: 'BEL',
    countryName: 'Bélgica',
    stadium: 'King Baudouin Stadium',
    date: '2026-09-04',
    endDate: '2026-09-05',
    isFinal: true,
    officialUrl: 'https://www.diamondleague.com/meetings/brussels/',
    events: [
      { id: 'brussels-100m-men', discipline: '100m', category: 'sprints', gender: 'men', results: [] },
      { id: 'brussels-100m-women', discipline: '100m', category: 'sprints', gender: 'women', results: [] },
      { id: 'brussels-1500m-men', discipline: '1500m', category: 'middle', gender: 'men', results: [] },
      { id: 'brussels-1500m-women', discipline: '1500m', category: 'middle', gender: 'women', results: [] },
      { id: 'brussels-pv-men', discipline: 'Salto com Vara', category: 'jumps', gender: 'men', results: [] },
      { id: 'brussels-lj-women', discipline: 'Salto em Distância', category: 'jumps', gender: 'women', results: [] },
    ],
  },
]
